type: infer
model: null
datasets:
  - datasets/uproof
trans_prompt: Translate this problem into Lean 4.
model_init_params:
  trust_remote_code: true
sampling_params:
  temperature: 0.9
  min_p: 0.05
  max_tokens: 2048
save_path: null
