type: sft-baseline
model: Qwen/Qwen2.5-Coder-7B
datasets:
  - internlm/Lean-Workbook
trans_prompt: Translate this math problem into formal language Lean 4.
log_dir: ./logs
sft_params:
  learning_rate: !!float 1e-6
  max_seq_length: 2048
  per_device_train_batch_size: 1
  save_steps: 1600
  bf16: true
  num_train_epochs: 1
  #  use_liger: true
  neftune_noise_alpha: 5
  model_init_kwargs:
    trust_remote_code: true
    torch_dtype: bfloat16
