def header():
    '''import Mathlib\n
    import Mathlib.Algebra.Algebra.Basic\n
    import Mathlib.Algebra.Order.Floor\n
    import Mathlib.Algebra.Associated\n
    import Mathlib.Algebra.BigOperators.Basic\n\n
    import Mathlib.Algebra.BigOperators.Pi\n
    import Mathlib.Algebra.GeomSum\n
    import Mathlib.Algebra.Group.Pi.Basic\n
    import Mathlib.Algebra.Group.Pi.Lemmas\n
    import Mathlib.Algebra.Group.Commute.Basic\n
    import Mathlib.Algebra.Group.Commute.Defs\n
    import Mathlib.Algebra.Group.Commute.Hom\n
    import Mathlib.Algebra.Group.Commute.Units\n
    import Mathlib.Algebra.GroupPower.Basic\n
    import Mathlib.Algebra.GroupPower.Identities\n
    import Mathlib.Algebra.Order.Floor\n
    import Mathlib.Algebra.QuadraticDiscriminant\n
    import Mathlib.Algebra.Ring.Basic\n
    import Mathlib.Analysis.MeanInequalitiesPow\n
    import Mathlib.Analysis.Asymptotics.AsymptoticEquivalent\n
    import Mathlib.Analysis.NormedSpace.Basic\n
    import Mathlib.Analysis.SpecialFunctions.Log.Basic\n
    import Mathlib.Analysis.SpecialFunctions.Log.Base\n
    import Mathlib.Combinatorics.SimpleGraph.Basic\n
    import Mathlib.Data.Complex.Basic\n
    import Mathlib.Data.Complex.Exponential\n
    import Mathlib.Data.Finset.Basic\n
    import Mathlib.Data.Fintype.Card\n\n
    import Mathlib.Data.Int.GCD\n
    import Mathlib.Data.Int.ModEq\n
    import Mathlib.Data.Int.Parity\n
    import Mathlib.Data.List.Intervals\n
    import Mathlib.Data.List.Palindrome\n
    import Mathlib.Data.Multiset.Basic\n\n
    import Mathlib.Data.Nat.Choose.Basic\n
    import Mathlib.Data.Nat.Digits\n
    import Mathlib.Data.Nat.Factorial.Basic\n
    import Mathlib.Data.Nat.Fib.Basic\n
    import Mathlib.Data.Nat.Fib.Zeckendorf\n
    import Mathlib.Data.Nat.ModEq\n
    import Mathlib.Data.Nat.Multiplicity\n
    import Mathlib.Data.Nat.Parity\n
    import Mathlib.Data.Nat.Prime\n
    import Mathlib.Data.PNat.Basic\n
    import Mathlib.Data.PNat.Prime\n\n
    import Mathlib.Data.Rat.BigOperators\n
    import Mathlib.Data.Rat.Cast.CharZero\n
    import Mathlib.Data.Rat.Cast.Defs\n
    import Mathlib.Data.Rat.Cast.Lemmas\n
    import Mathlib.Data.Rat.Cast.Order\n
    import Mathlib.Data.Rat.Defs\n
    import Mathlib.Data.Rat.Denumerable\n
    import Mathlib.Data.Rat.Encodable\n
    import Mathlib.Data.Rat.Field\n
    import Mathlib.Data.Rat.Floor\n
    import Mathlib.Data.Rat.Init\n
    import Mathlib.Data.Rat.Lemmas\n
    import Mathlib.Data.Rat.Order\n
    import Mathlib.Data.Rat.Sqrt\n\n
    import Mathlib.Data.Rat.Star\n
    import Mathlib.Data.Real.Basic\n
    import Mathlib.Data.ENNReal.Basic\n
    import Mathlib.Data.ENNReal.Inv\n
    import Mathlib.Data.ENNReal.Operations\n
    import Mathlib.Data.ENNReal.Real\n
    import Mathlib.Data.Real.ENatENNReal\n
    import Mathlib.Data.Real.Irrational\n
    import Mathlib.Data.Real.NNReal\n
    import Mathlib.Data.Real.Sqrt\n\n
    import Mathlib.Data.Set.Finite\n
    import Mathlib.Data.Sym.Sym2\n
    import Mathlib.Data.ZMod.Basic\n
    import Mathlib.Dynamics.FixedPoints.Basic\n\n
    import Mathlib.LinearAlgebra.AffineSpace.AffineMap\n
    import Mathlib.LinearAlgebra.AffineSpace.Independent\n
    import Mathlib.LinearAlgebra.AffineSpace.Ordered\n
    import Mathlib.LinearAlgebra.FiniteDimensional\n
    import Mathlib.Logic.Equiv.Basic\n\n
    import Mathlib.Order.Filter.Basic\n\n
    import Mathlib.Order.WellFounded\n
    import Mathlib.Topology.Basic\n
    import Mathlib.Topology.Instances.NNReal\n\n
    import Mathlib.Data.ZMod.Basic\n
    import Mathlib.RingTheory.Int.Basic\n\n
    import Aesop\n
    import ProofWidgets\n\n
    set_option maxHeartbeats 0\n
    open Topology\n
    open BigOperators\n
    open Nat\n
    open Real\n
    open Rat\n
    '''

    return 'import Mathlib\nimport Aesop\nset_option maxHeartbeats 0\nopen Topology\nopen BigOperators\nopen Nat\nopen Real\nopen Rat\n'